package org.ns.npersistence;

import java.lang.annotation.Annotation;
import java.lang.reflect.Field;

class PrimaryKeyAttributeProcessorInsert {
    public void process(NTableInsert table, Field field, Annotation annotation) throws Exception {
        table.setInsertQuery(table.getCurrentInsertQuery().values("pk_" + field.getName()));

        if ((boolean) AnnotationToolkit.getAnnotationValue(annotation, "autoGenerated")) {
            int pk = (int) field.get(table.getCurrentObjectInstance());
            if (pk == 0)
                field.set(table.getCurrentObjectInstance(),
                        NPrimaryKeyGenerator.getDefault().getPrimaryKey(table.getSqlName()));
            else NPrimaryKeyGenerator.getDefault().setLastGeneratedPrimaryKey(pk);
        }

        table.addObject(field.get(table.getCurrentObjectInstance()));
        table.setPrimaryKey(field.get(table.getCurrentObjectInstance()));
    }
}
