package org.ns.test;

import java.util.ArrayList;

import org.ns.npersistence.IterableConstants;
import org.ns.npersistence.annotations.AtomicAttribute;
import org.ns.npersistence.annotations.IterableAttribute;
import org.ns.npersistence.annotations.PrimaryKey;
import org.ns.npersistence.annotations.Table;

@Table
public class Nutzer {
	
	@PrimaryKey(autoGenerated = true)
	private int id;

	@AtomicAttribute
	private String name;
	
	@IterableAttribute(mappingType = IterableConstants.ARRAYLIST)
	private ArrayList<Buch> buecher = new ArrayList<Buch>();

	public void setId(int value) {
		id = value;
	}
	
	public int getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	public void AddBuch(Buch buch) {
		this.buecher.add(buch);
	}

}
